# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydRgvJer0-uJDneLDN-lYQqneomBxLBZ
"""

# -*- coding: utf-8 -*-
"""NLP AISAP Chatbot """

!pip install pandas datasets transformers torch accelerate sentencepiece evaluate

import os
import pandas as pd
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
)

# --- CONFIGURATION ---
DATA_PATH = "aisap_dataset.csv"
MODEL_NAME = "google/flan-t5-base"
OUTPUT_DIR = "flan-t5-ai-simple-bot"

def main():
    print(f"Loading dataset from {DATA_PATH}...")

    # 1. Load Dataset
    data_files = {"train": DATA_PATH}
    # Check if file exists first to avoid confusing errors
    if not os.path.exists(DATA_PATH):
        print(f"ERROR: File {DATA_PATH} not found. Please run the 'dataset generation' script first.")
        return

    raw_datasets = load_dataset("csv", data_files=data_files)
    raw_datasets = raw_datasets["train"].train_test_split(test_size=0.1, seed=42)

    # 2. Setup Model & Tokenizer
    print(f"Loading Model: {MODEL_NAME}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

    max_input_length = 256
    max_target_length = 256

    def preprocess_function(examples):
        # Instruction Tuning Prefix
        prefix = "Explain this AI concept with an analogy: "

        inputs = [prefix + str(doc) for doc in examples["category"]]
        targets = [str(doc) for doc in examples["simple_explanation"]]

        # Tokenize inputs
        model_inputs = tokenizer(
            inputs,
            max_length=max_input_length,
            truncation=True
        )

        # Tokenize targets (Updated to fix the warning you saw)
        labels = tokenizer(
            text_target=targets,
            max_length=max_target_length,
            truncation=True
        )

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs

    print("Tokenizing data...")
    tokenized_datasets = raw_datasets.map(
        preprocess_function,
        batched=True,
        remove_columns=raw_datasets["train"].column_names,
    )

    # 3. Training Setup
    data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

    training_args = Seq2SeqTrainingArguments(
        output_dir=OUTPUT_DIR,
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=3e-4,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        gradient_accumulation_steps=1,
        weight_decay=0.01,
        save_total_limit=2,
        num_train_epochs=15,
        predict_with_generate=True,
        fp16=False,
        logging_steps=50,
        push_to_hub=False,
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_datasets["train"],
        eval_dataset=tokenized_datasets["test"],
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    # 4. Train
    print("Starting training...")
    trainer.train()

    # 5. Save
    print("Saving model...")
    trainer.save_model(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)

    # 6. Start Chat
    chat(OUTPUT_DIR)

def chat(model_dir):
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

    # Reload the trained model
    tokenizer = AutoTokenizer.from_pretrained(model_dir)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_dir)

    print("\n" + "="*40)
    print("AISAP Bot Ready! (Type 'quit' to exit)")
    print("="*40)

    while True:
        user_input = input("\nYou: ")
        if user_input.lower() in ["quit", "exit"]:
            break

        # Must match the training prefix
        prompt = f"Explain this AI concept with an analogy: {user_input}"

        inputs = tokenizer(
            prompt,
            return_tensors="pt",
            truncation=True,
            max_length=256
        )

        output_ids = model.generate(
            **inputs,
            max_new_tokens=128,
            num_beams=5,
            temperature=0.7,
            early_stopping=True
        )

        answer = tokenizer.decode(output_ids[0], skip_special_tokens=True)
        print(f"Bot: {answer}")

if __name__ == "__main__":
    main()